---
title: "Data"
output: html_document
---
Data Source: [Global Youtube Statistics 2023](https://www.kaggle.com/datasets/nelgiriyewithana/global-youtube-statistics-2023)\
- `id`: Position of the YouTube channel based on the number of subscribers\
- `subscribers`: Number of subscribers to the channel\
- `video views`: Total views across all videos on the channel\
- `category`: Category or niche of the channel\
- `uploads`: Total number of videos uploaded on the channel\
- `country`: Country where the YouTube channel originates\
- `channel_type`: Type of the YouTube channel (e.g., individual, brand)\
- `video_views_rank`: Ranking of the channel based on total video views\
- `country_rank`: Ranking of the channel based on the number of subscribers within its country\
- `channel_type_rank`: Ranking of the channel based on its type (individual or brand)\
- `video_views_for_the_last_30_days`: Total video views in the last 30 days\
- `lowest_monthly_earnings`: Lowest estimated monthly earnings from the channel\
- `highest_monthly_earnings`: Highest estimated monthly earnings from the channel\
- `lowest_yearly_earnings`: Lowest estimated yearly earnings from the channel\
- `highest_yearly_earnings`: Highest estimated yearly earnings from the channel\
- `subscribers_for_last_30_days`: Number of new subscribers gained in the last 30 days\
- `created_year`: Year when the YouTube channel was created\
- `population`: Total population of the country\
- `latitude`: Latitude coordinate of the country's location\
- `longitude`: Longitude coordinate of the country's location\